Santhosh, Rajashri | #12 | add bahmni-analytics.conf file

diff --git a/scripts/rpm/bahmni-analytics b/scripts/rpm/bahmni-analytics
--- a/scripts/rpm/bahmni-analytics
+++ b/scripts/rpm/bahmni-analytics
@@ -1,7 +1,13 @@
 #!/bin/bash
 
-. /etc/bahmni-installer/bahmni.conf
+. /opt/bahmni-analytics/conf/bahmni-analytics.conf
 
 echo "Running bahmni-analytics..."
 java -DOPENMRS_DB_SERVER=${OPENMRS_DB_SERVER} -DOPENMRS_DB_USER=${OPENMRS_DB_USERNAME} -DOPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD} -jar /opt/bahmni-analytics/libs/bahmni-analytics-*.jar >> /opt/bahmni-analytics/log/bahmni-analytics.log
-echo "Done"
+   if [  $? == 0 ]
+then
+    echo "batch successfully completed"
+else
+    echo "batch failed : /opt/bahmni-analytics/log/bahmni-analytics.log"
+fi
+
